src/main/scala/nutcore/EmbeddedTLB.scala
src/main/scala/nutcore/TLB.scala

the bug will not caused with legal code.
the check is at spec-priv 4.3.1:Addressing and Memory Protection
"Irrespective of SUM, the supervisor may not execute code on pages
with U=1"

TLB: fix bug of permission check: Smode exec user page code

---

src/main/scala/device/AXI4DummySD.scala

This pull requests modifies inline SDHelper module in AXI4DummySD.
It uses always@(nededge clk) to support async reading and holding data.
This pull request should fixed compilation errors on Verilator v4.108.

device,sdcard: improve inline SDHelper coding style 

---

fpga/boot/README.md

Pulling device-tree-xlnx repo without specifying the branch can produce  `invalid command name: hsi::utils::get_rp_rm_for_drv"`  error  in Vivado 2019.1 due to not compatible versions.

fpga: specify the version of device-tree-xlnx repo

---

fpga/board/common.tcl
fpga/board/pynq/mk.tcl

Hi, the first commit in this PR removes monitor.v, which was removed since the newer difftest framework was adopted in #63. The second adds difftest stubs files to the project, so the `module not found` error in Vivado can be resolved.

fpga: update Vivado project files

---

src/main/scala/bus/simplebus/Crossbar.scala
src/main/scala/system/NutShell.scala

The changed module
- supports overlapping address ranges
- won't output `X` state on `io.out(i).resp.ready` signals
- shortens combinational logic because the changed code selects output bus with one-hot multiplexer rather than encoded index `outSelIdx`
The order of address range in MMIO crossbar is also changed. This is because in some settings address range of external devices can be extremely large and contains CLINT and PLIC. These internal devices, who has smaller address range should have higher priority in this situation.
New module has been tested in simulation.

bus/crossbar: refactor module SimpleBusCrossbar1toN

---

src/main/scala/nutcore/mem/EmbeddedTLB.scala

This patch fixes errors generated when TLBs are disabled (#79). Changes are based on [this comment](https://github.com/OSCPU/NutShell/issues/73#issuecomment-1061337589) in #73.

mem/EmbeddedTLB: fix connections of module EmbeddedTLB_fake

---

src/main/scala/bus/simplebus/Crossbar.scala

this prevents X-propagation in simulation

simplebus/crossbar: clear inflightSrc register during reset

---

src/main/scala/nutcore/backend/fu/CSR.scala

The least significant bit of mepc should be zero. This is a temp fix to co-simulate ready-to-run/microbench.bin with Spike.

CSR: initialize mepc to zero

---

src/main/scala/device/AXI4CLINT.scala
src/main/scala/device/AXI4DMA.scala
src/main/scala/device/AXI4DummySD.scala
src/main/scala/device/AXI4PLIC.scala
src/main/scala/device/AXI4UART.scala
src/main/scala/nutcore/backend/fu/CSR.scala
src/main/scala/sim/MeipGen.scala
src/main/scala/utils/BitUtils.scala

Previously the MaskExpand utility does not check the width of input date, output data, and writable mask. This would cause data loss at most significant bits.

utils: fix the unaligned writable data masks

---

src/main/scala/sim/NutShellSim.scala
src/main/scala/top/TopMain.scala

This would allow the finish function to implement hardware logics within the elaboration scope.

Move DifftestModule.finish to the top-level module

---

.github/workflows/main.yml
Makefile

When CHISEL_VERSION=6.x, we cannot specify mill-outputfile. Rename outputfile in `make verilog`, and split-verilog in both `make emu` and `make verilog`.

MakeFile & CI: support chisel-cross in make verilog and add CI test

---

src/main/scala/device/AXI4VGA.scala

Disable FBhelper when no rw in AXI4VGA, to avlid large number of calls to put_pixel empty functions

FBhelper: disable when no rw in AXI4VGA

---

Makefile

Verilator will abort the simulation if $error is triggered.

makefile: replace error with fwrite

---

src/main/scala/nutcore/NutCoreTrap.scala

This change avoids the NEMU_TRAP instructions to modify the architectural states. It is also decoded with I-Type which does not update the register file.

Decode NEMU_TRAP with alu.add

---

src/main/scala/sim/NutShellSim.scala
src/main/scala/utils/Debug.scala

Avoid the large number of timer counters and global enable wirings.

Debug: use LogPerfControl from difftest

---

src/main/scala/bus/axi4/AXI4.scala
src/main/scala/bus/simplebus/ToAXI4.scala
src/main/scala/device/AXI4DMA.scala
src/main/scala/nutcore/Bundle.scala
src/main/scala/nutcore/Decode.scala
src/main/scala/nutcore/backend/fu/CSR.scala
src/main/scala/nutcore/frontend/IDU.scala
src/main/scala/nutcore/isa/Privileged.scala
src/main/scala/nutcore/mem/EmbeddedTLB.scala
src/main/scala/nutcore/mem/TLB.scala

Typo: priviledged -> privileged.

Fix typo for privileged

---

src/main/scala/nutcore/backend/fu/ALU.scala

According to the RISC-V spec, JALR sets the least-significant bit of the jump target address to zero.

ALU: mask off bit[0] for jump target

---

src/main/scala/device/AXI4RAM.scala
src/main/scala/nutcore/NutCore.scala

Difftest will refactor the DifftestMem implementation and remove this argument. To avoid CI failures, we remove this.

AXI4RAM: remove the synthesizable option

---

src/main/scala/device/AXI4RAM.scala
src/main/scala/sim/NutShellSim.scala

Use a larger RAM to run modern workloads. We also improve the code quality of index in AXI4RAM.

NutShellSim: use 2GB AXI4RAM

---

.github/workflows/main.yml
Makefile
fpga/NutShell.tcl
fpga/board/PXIe/bd/arm.tcl
fpga/board/axu3cg/bd/arm.tcl
fpga/board/common.tcl
fpga/board/pynq/bd/standalone.tcl
src/main/scala/nutcore/backend/fu/CSR.scala
src/main/scala/top/Settings.scala
src/main/scala/utils/Debug.scala

The master branch of NutShell can not generate an FPGA project that provides correct functionality(#205 #204  #200 ). Therefore I made serval changes to the NutShell and the FPGA project tcl. 
1. For software simulation, NutShell uses the `nutcoretrap` in CSR as a signal to dump the statistic during the simulation, this signal is connected by the boringUtil. However, the source of this connection is missing when using the FPGA platform. I set `nutcoretrap` signal to zero when using FPGA.
2. Vivado can automatically identify the signals for AXI protocol if the name of these signals follow a certain form, the early version of NutShell uses a `sed` command in Makefile to convert the Chisel name to the specific form of AXI Signals. However, after using `--spilt-verilog` option, not all the …

NutShell master branch re-adaption for FPGA platforms

---

src/test/scala/TopMain.scala

Chisel v7.0.0 wraps Verification primitives in a verification layer. The generated file should be included by a filelist. To simplify this, we enable all layers by default in NutShell.

top: enable all layers by default
